In [1]:
!pip install numpy

Numpy is used for scientific computation and having many inbuilt mathematical functions that can operate on arrays,matrices and vectorized operations.
--very very fast in mathematical functions

In [2]:
import numpy as np

#create array using numpy
#create single dimensional array
list1=[1,2,3,4,5,6]
arr1=np.array(list1)
print(arr1)
print(type(arr1))
print(arr1.shape) #(6,) it refers to single dimensional array  #blank after comma  #no specific rows and columns its just 6 elements

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [9]:
#convert to 2D array
arr1.reshape(1,6)  # 1 row, 6 coln 2D array having 2 braces --> array([[1, 2, 3, 4, 5, 6]])
#manually create
arr1=np.array([[1,2,3,4,5,6]])
print(arr1.shape) #(1, 6)
print(arr1)

(1, 6)
[[1 2 3 4 5 6]]


In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2.shape)
print(arr2)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [16]:
#In built array function
arr3=np.arange(0,10,2)
print(arr3) # 1D
arr3.reshape(1,5) #2D

#np.ones(rows,coln)
arr4=np.ones((2,3))
print(arr4)

#np.zeros(rows,coln)
arr5=np.zeros((2,3))
print(arr5)
#identity matrices
arr6=np.eye(3,3) #diagonal 1 and rest is zero
print(arr6)

[0 2 4 6 8]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print("array:\n",arr)
print("dimension:",arr.ndim)
print("shape",arr.shape)
print("size/elements:",arr.size)

array:
 [[1 2 3]
 [4 5 6]]
dimension: 2
shape (2, 3)
size/elements: 6


Vectorized Operations: A High-Performance Approach to Computation
Vectorized operations refer to performing mathematical operations on entire arrays (vectors, matrices) at once, rather than using loops to operate element by element. This approach significantly boosts performance, especially in numerical computing and machine learning.

In [5]:
#Vectorized operations in numpy
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("addition \n",arr1+arr2)
print("multiplication \n",arr1*arr2)
print("substraction \n",arr1-arr2)
print("division \n",arr1/arr2)

#Note: element wise operation thatmeans element of same index will compute together

addition 
 [ 7  9 11 13 15]
multiplication 
 [ 6 14 24 36 50]
substraction 
 [-5 -5 -5 -5 -5]
division 
 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Universal function that applies on entire array
The exponential function calculates
e to the power x , where 𝑒≈2.718
e≈2.718.

In [6]:
arr=np.array([1,2,3,4,5])
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [13]:
#slicing and indexing operations

arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [33]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[0][0])#1
print(arr[0][1:3])#2,3

print(arr[1:3,2:4]) #8 9 13 14
print(arr[1:,2:4]) #8 9 13 14
print("9 10 14 15: \n",arr[1:,3:])

1
[2 3]
[[ 8  9]
 [13 14]]
[[ 8  9]
 [13 14]]
9 10 14 15: 
 [[ 9 10]
 [14 15]]


In [40]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)

#Modifications
arr[0][0]=100
print("Modified 1: \n",arr)

arr[0][1:5]=200
print("Modified 2: \n",arr)

arr[1:]=300
print("Modified 3: \n",arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Modified 1: 
 [[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]
Modified 2: 
 [[100 200 200 200 200]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]
Modified 3: 
 [[100 200 200 200 200]
 [300 300 300 300 300]
 [300 300 300 300 300]]


statistical concept NORMALIZATION
mean is zero and standard deviation is one

In [44]:
#Normalization
arr=np.array([1,2,3,4,5])
mean=np.mean(arr)
std=np.std(arr)
print("mean:",mean)
print("standard deviation:",std)
print("normalized array: \n",(arr-mean)/std)
print("variance ",np.var(arr))

mean: 3.0
standard deviation: 1.4142135623730951
normalized array: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
variance  2.0


In [50]:
#Logical operation
data=np.array([1,2,3,4,5])
print(data>2)
print(data[data>2])
print(data[(data>2) & (data<5)])


[False False  True  True  True]
[3 4 5]
[3 4]
